<?php
/**
 * @file
 * Contains module hooks.
 */

/**
 * Implements hook_theme().
 *
 * Add template for block.
 */
function aarhus_hero_theme($existing, $type, $theme, $path) {
  return [
    'aarhus_hero_block' => [
      'template' => 'aarhus-hero-block',
      'variables' => ['config' => NULL, 'image' => NULL],
    ],
    'aarhus_hero_video_block' => [
      'template' => 'aarhus-hero-video-block',
      'variables' => ['video' => NULL, 'video_title' => NULL, 'video_description' => NULL],
    ],
  ];
}
